name: Build and Deploy to Selectel S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build # Эта команда ОБЯЗАТЕЛЬНО должна создать папку ./dist

    - name: Deploy dist folder to Selectel S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SELECTEL_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SELECTEL_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-7
      run: |
        aws s3 sync ./dist s3://${{ secrets.SELECTEL_BUCKET_NAME }} \
          --endpoint-url=https://s3.ru-7.storage.selcloud.ru \
          --delete
