name: Build and Deploy to Selectel S3

on:
  push:
    branches:
      - main # Триггер на пуш в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем актуальный код из вашего репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Настраиваем окружение Node.js (версия 24, чтобы не было варнингов)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'

    # 3. Чистая установка всех ваших зависимостей (Tailwind, Vite и т.д.)
    - name: Install dependencies
      run: npm ci

    # 4. Запуск сборщика Vite (он создаст ту самую папку ./dist и положит туда скомпилированный HTML/CSS)
    - name: Build project
      run: npm run build

    # 5. Деплой сгенерированной папки ./dist напрямую в S3 Selectel
    - name: Deploy dist folder to Selectel S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SELECTEL_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SELECTEL_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ru-7
      run: |
        aws s3 sync ./dist s3://${{ secrets.SELECTEL_BUCKET_NAME }} \
          --endpoint-url=https://selcloud.ru \
          --delete
